package io.github.cyfko.veridot.databases;

import io.github.cyfko.veridot.core.Broker;
import io.github.cyfko.veridot.core.exceptions.VeridotException;
import io.github.cyfko.veridot.core.impl.Envelope;
import io.github.cyfko.veridot.core.impl.Scope;
import io.github.cyfko.veridot.core.impl.ErrorCode;
import javax.sql.DataSource;
import java.nio.charset.StandardCharsets;
import java.sql.*;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.logging.Logger;

/**
 * SQL Database implementation of the Broker interface for Protocol V4 (§12.2).
 */
public class DatabaseBroker implements Broker {

    private static final Logger logger = Logger.getLogger(DatabaseBroker.class.getName());

    private final DataSource dataSource;
    private final String tableName;
    private final UpsertDialect upsertDialect;

    // Local cache to bypass read-after-write latencies on the signing node
    private final Map<String, byte[]> localCache = new ConcurrentHashMap<>();

    private enum UpsertDialect {
        POSTGRES_H2,
        MYSQL,
        ORACLE,
        SQL_SERVER
    }

    public DatabaseBroker(DataSource dataSource, String tableName) {
        if (dataSource == null) {
            throw new IllegalArgumentException("DataSource cannot be null");
        }
        if (tableName == null || !tableName.matches("^[a-zA-Z][a-zA-Z0-9_]*$")) {
            throw new IllegalArgumentException("Invalid table name: " + tableName);
        }
        this.dataSource = dataSource;
        this.tableName = tableName;
        this.upsertDialect = detectDialect();
        createBrokerTableIfNotExists();
    }

    private UpsertDialect detectDialect() {
        try (Connection conn = dataSource.getConnection()) {
            String dbProduct = conn.getMetaData().getDatabaseProductName().toLowerCase();
            if (dbProduct.contains("postgresql") || dbProduct.contains("h2")) {
                return UpsertDialect.POSTGRES_H2;
            } else if (dbProduct.contains("mysql")) {
                return UpsertDialect.MYSQL;
            } else if (dbProduct.contains("oracle")) {
                return UpsertDialect.ORACLE;
            } else if (dbProduct.contains("sql server")) {
                return UpsertDialect.SQL_SERVER;
            } else {
                throw new UnsupportedOperationException("Unsupported DB for upsert: " + dbProduct);
            }
        } catch (SQLException e) {
            throw new RuntimeException("Cannot detect database dialect", e);
        }
    }

    private void createBrokerTableIfNotExists() {
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData meta = connection.getMetaData();
            String dbProduct = meta.getDatabaseProductName().toLowerCase();

            String idDefinition;
            String keyType;
            String valType;
            String updatedAtDefinition;

            if (dbProduct.contains("postgresql") || dbProduct.contains("h2")) {
                idDefinition = "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
                keyType = "BYTEA NOT NULL UNIQUE";
                valType = "BYTEA NOT NULL";
                updatedAtDefinition = "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP";
            } else if (dbProduct.contains("mysql")) {
                idDefinition = "id BIGINT AUTO_INCREMENT PRIMARY KEY";
                keyType = "VARBINARY(767) NOT NULL UNIQUE"; // Safe max unique index size
                valType = "LONGBLOB NOT NULL";
                updatedAtDefinition = "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP";
            } else if (dbProduct.contains("oracle")) {
                idDefinition = "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
                keyType = "RAW(2000) NOT NULL UNIQUE";
                valType = "BLOB NOT NULL";
                updatedAtDefinition = "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP";
            } else if (dbProduct.contains("sql server")) {
                idDefinition = "id BIGINT IDENTITY(1,1) PRIMARY KEY";
                keyType = "VARBINARY(900) NOT NULL UNIQUE"; // Max unique index key length on older SQL Server
                valType = "VARBINARY(MAX) NOT NULL";
                updatedAtDefinition = "updated_at DATETIME DEFAULT GETDATE()";
            } else {
                throw new UnsupportedOperationException("Unsupported DB: " + dbProduct);
            }

            String ddl;
            if (dbProduct.contains("sql server")) {
                ddl = String.format("""
                IF NOT EXISTS (
                    SELECT * FROM INFORMATION_SCHEMA.TABLES
                    WHERE TABLE_NAME = '%s'
                )
                BEGIN
                    CREATE TABLE %s (
                        %s,
                        storage_key %s,
                        entry_bytes %s,
                        %s
                    )
                END
                """, tableName, tableName, idDefinition, keyType, valType, updatedAtDefinition);
            } else {
                ddl = String.format("""
                CREATE TABLE IF NOT EXISTS %s (
                    %s,
                    storage_key %s,
                    entry_bytes %s,
                    %s
                )
                """, tableName, idDefinition, keyType, valType, updatedAtDefinition);
            }

            try (Statement stmt = connection.createStatement()) {
                stmt.execute(ddl);
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to initialize database broker table", e);
        }
    }

    @Override
    public CompletableFuture<Void> put(byte[] storageKey, byte[] envelopeBytes) {
        if (storageKey == null || envelopeBytes == null) {
            throw new IllegalArgumentException("storageKey and envelopeBytes cannot be null");
        }

        if (envelopeBytes.length == 0) {
            localCache.remove(toHexKey(storageKey));
            return CompletableFuture.runAsync(() -> {
                try (Connection conn = dataSource.getConnection()) {
                    String sql = String.format("DELETE FROM %s WHERE storage_key = ?", tableName);
                    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                        stmt.setBytes(1, storageKey);
                        stmt.executeUpdate();
                    }
                } catch (SQLException e) {
                    throw new VeridotException(ErrorCode.TRANSPORT_UNAVAILABLE, null, "Database transport failure on delete()", e);
                }
            });
        }

        // Validate envelope well-formedness before saving (§12.2)
        try {
            Envelope.parse(envelopeBytes);
        } catch (VeridotException e) {
            return CompletableFuture.failedFuture(e);
        } catch (Exception e) {
            return CompletableFuture.failedFuture(new VeridotException(ErrorCode.INVALID_ENVELOPE, null, "Failed to parse envelope bytes", e));
        }

        return CompletableFuture.runAsync(() -> {
            try (Connection conn = dataSource.getConnection()) {
                String sql = buildUpsertSql();
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setBytes(1, storageKey);
                    stmt.setBytes(2, envelopeBytes);
                    stmt.executeUpdate();
                }
            } catch (SQLException e) {
                throw new VeridotException(ErrorCode.TRANSPORT_UNAVAILABLE, null, "Database transport failure on put()", e);
            }
        });
    }

    @Override
    public byte[] get(byte[] storageKey) {
        if (storageKey == null) {
            return null;
        }

        // Check local cache first
        String cacheKey = toHexKey(storageKey);
        byte[] cached = localCache.get(cacheKey);
        if (cached != null) {
            return cached;
        }

        try (Connection conn = dataSource.getConnection()) {
            String sql = String.format("SELECT entry_bytes FROM %s WHERE storage_key = ?", tableName);
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setBytes(1, storageKey);
                try (ResultSet rs = stmt.executeQuery()) {
                    if (rs.next()) {
                        byte[] bytes = rs.getBytes("entry_bytes");
                        // Warm cache
                        localCache.put(cacheKey, bytes);
                        return bytes;
                    }
                    return null;
                }
            }
        } catch (SQLException e) {
            logger.severe("Database error on get(): " + e.getMessage());
            throw new VeridotException(ErrorCode.TRANSPORT_UNAVAILABLE, null, "Database transport failure on get()", e);
        }
    }

    @Override
    public List<BrokerEntry> snapshot(Scope scope) {
        if (scope == null) {
            throw new IllegalArgumentException("Scope cannot be null");
        }

        byte[] scopeBytes = scope.value().getBytes(StandardCharsets.UTF_8);
        byte[] lowerBound = new byte[scopeBytes.length + 1];
        System.arraycopy(scopeBytes, 0, lowerBound, 0, scopeBytes.length);
        lowerBound[scopeBytes.length] = 0x00; // Separator NUL byte

        // Upper bound is the scope bytes followed by 0x01 to cover all entry types and keys in this scope
        byte[] upperBound = new byte[scopeBytes.length + 1];
        System.arraycopy(scopeBytes, 0, upperBound, 0, scopeBytes.length);
        upperBound[scopeBytes.length] = 0x01;

        List<BrokerEntry> list = new ArrayList<>();
        try (Connection conn = dataSource.getConnection()) {
            String sql = String.format("SELECT storage_key, entry_bytes FROM %s WHERE storage_key >= ? AND storage_key < ?", tableName);
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setBytes(1, lowerBound);
                stmt.setBytes(2, upperBound);
                try (ResultSet rs = stmt.executeQuery()) {
                    while (rs.next()) {
                        list.add(new BrokerEntry(rs.getBytes("storage_key"), rs.getBytes("entry_bytes")));
                    }
                }
            }
        } catch (SQLException e) {
            logger.severe("Database error on snapshot(): " + e.getMessage());
            throw new VeridotException(ErrorCode.TRANSPORT_UNAVAILABLE, null, "Database transport failure on snapshot()", e);
        }

        return list;
    }

    @Override
    public void putLocal(byte[] storageKey, byte[] envelopeBytes) {
        if (storageKey != null && envelopeBytes != null) {
            localCache.put(toHexKey(storageKey), envelopeBytes);
        }
    }

    private String buildUpsertSql() {
        return switch (upsertDialect) {
            case POSTGRES_H2 -> String.format(
                    "INSERT INTO %s (storage_key, entry_bytes) VALUES (?, ?) ON CONFLICT (storage_key) DO UPDATE SET entry_bytes = EXCLUDED.entry_bytes",
                    tableName);
            case MYSQL -> String.format(
                    "INSERT INTO %s (storage_key, entry_bytes) VALUES (?, ?) ON DUPLICATE KEY UPDATE entry_bytes = VALUES(entry_bytes)",
                    tableName);
            case ORACLE -> String.format(
                    "MERGE INTO %s t USING (SELECT ? AS k, ? AS v FROM DUAL) s ON (t.storage_key = s.k) "
                            + "WHEN MATCHED THEN UPDATE SET t.entry_bytes = s.v "
                            + "WHEN NOT MATCHED THEN INSERT (storage_key, entry_bytes) VALUES (s.k, s.v)",
                    tableName);
            case SQL_SERVER -> String.format(
                    "MERGE INTO %s WITH (HOLDLOCK) AS t USING (SELECT ? AS k, ? AS v) AS s ON (t.storage_key = s.k) "
                            + "WHEN MATCHED THEN UPDATE SET t.entry_bytes = s.v "
                            + "WHEN NOT MATCHED THEN INSERT (storage_key, entry_bytes) VALUES (s.k, s.v);",
                    tableName);
        };
    }

    private static String toHexKey(byte[] bytes) {
        return HexFormat.of().formatHex(bytes);
    }
}
