package io.github.cyfko.veridot.databases;

import io.github.cyfko.veridot.core.MetadataBroker;
import io.github.cyfko.veridot.core.exceptions.BrokerExtractionException;

import javax.sql.DataSource;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Logger;


/**
 * A {@link MetadataBroker} implementation that stores and retrieves messages
 * using a relational SQL database. This broker is useful in distributed environments where
 * consistent message delivery and verification are required across microservices or service replicas.
 *
 * <p>This implementation supports:</p>
 * <ul>
 *     <li>Automatic creation of the broker table if it does not already exist</li>
 *     <li>Configurable table name, validated to prevent SQL injection</li>
 *     <li>Asynchronous message storage and retrieval using {@link java.util.concurrent.CompletableFuture}</li>
 *     <li>Compatibility with major relational databases (PostgreSQL, MySQL, SQL Server, H2)</li>
 * </ul>
 *
 * <h2>Usage</h2>
 *
 * <pre>{@code
 * DataSource dataSource = ...;
 * String tableName = "broker_messages";
 * DatabaseBroker broker = new DatabaseBroker(dataSource, tableName);
 * }</pre>
 *
 * <h2>Table Schema</h2>
 *
 * <pre>{@code
 * CREATE TABLE broker_messages (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   message_key VARCHAR(255) NOT NULL,
 *   message_value TEXT NOT NULL,
 *   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
 * );
 * }</pre>
 *
 * <p>This broker is particularly well-suited to high-availability setups involving:</p>
 * <ul>
 *     <li>Clustered databases with automatic failover</li>
 *     <li>Sharded deployments using consistent hashing or range partitioning</li>
 *     <li>Single-node monoliths where persistence is required</li>
 * </ul>
 *
 * <p>Note: Message keys must be unique. If a key is reused, the insertion will fail with a primary key violation.</p>
 *
 * @author Frank KOSSI
 * @since 1.0.0
 */
public class DatabaseMetadataBroker implements MetadataBroker {
    private static final String COLUMN_KEY = "message_key";
    private static final String COLUMN_MESSAGE = "message_value";
    private static final Logger logger = Logger.getLogger(DatabaseMetadataBroker.class.getName());

    private final DataSource dataSource;
    private final String tableName;

    /**
     * Constructs a {@code DatabaseMetadataBroker} backed by the given {@link DataSource}.
     *
     * <p>The broker table is created automatically if it does not already exist.  The table
     * name is validated at construction time to prevent SQL injection.</p>
     *
     * <pre>{@code
     * DataSource ds = ...; // e.g., HikariCP, Spring DataSource
     * MetadataBroker broker = new DatabaseMetadataBroker(ds, "veridot_broker");
     * }</pre>
     *
     * @param dataSource a JDBC {@link DataSource} connected to a supported database
     *                   (PostgreSQL, MySQL, H2, Oracle, SQL Server); must not be {@code null}
     * @param tableName  the name of the broker table; must start with a letter and contain
     *                   only letters, digits, or underscores (validated against SQL injection)
     * @throws IllegalArgumentException if {@code tableName} fails the naming validation
     * @throws RuntimeException         if the table cannot be created (SQL error)
     */
    public DatabaseMetadataBroker(DataSource dataSource, String tableName) {
        if (!isValidTableName(tableName)) {
            throw new IllegalArgumentException(String.format("Invalid table name: [%s]. Should start with a letter and only contains letters, digits or underscore.", tableName));
        }
        this.dataSource = dataSource;
        this.tableName = tableName;
        createBrokerTableIfNotExists();
    }

    private boolean isValidTableName(String tableName) {
        // Allow only alphanumeric characters and underscores, and must start with a letter
        return tableName != null && tableName.matches("^[a-zA-Z][a-zA-Z0-9_]*$");
    }

    private void createBrokerTableIfNotExists() {
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData meta = connection.getMetaData();
            String dbProduct = meta.getDatabaseProductName().toLowerCase();

            String idDefinition;
            String createdAtDefinition;

            if (dbProduct.contains("postgresql") || dbProduct.contains("h2")) {
                idDefinition = "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
                createdAtDefinition = "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP";
            } else if (dbProduct.contains("mysql")) {
                idDefinition = "id BIGINT AUTO_INCREMENT PRIMARY KEY";
                createdAtDefinition = "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP";
            } else if (dbProduct.contains("oracle")) {
                idDefinition = "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
                createdAtDefinition = "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"; // Oracle 12c+
            } else if (dbProduct.contains("sql server")) {
                idDefinition = "id BIGINT IDENTITY(1,1) PRIMARY KEY";
                createdAtDefinition = "created_at DATETIME DEFAULT GETDATE()";
            } else {
                throw new UnsupportedOperationException("Unsupported DB: " + dbProduct);
            }

            String ddl = asDDL(dbProduct, idDefinition, createdAtDefinition);

            try (Statement stmt = connection.createStatement()) {
                stmt.execute(ddl);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private String asDDL(String dbProduct, String idDefinition, String createdAtDefinition) {
        if (dbProduct.contains("sql server")) {
            return String.format("""
            IF NOT EXISTS (
                SELECT * FROM INFORMATION_SCHEMA.TABLES
                WHERE TABLE_NAME = '%s'
            )
            BEGIN
                CREATE TABLE %s (
                    %s,
                    %s VARCHAR(255) NOT NULL UNIQUE,
                    %s TEXT NOT NULL,
                    %s
                )
            END
            """, tableName, tableName, idDefinition, COLUMN_KEY, COLUMN_MESSAGE, createdAtDefinition);
        }

        return String.format("""
        CREATE TABLE IF NOT EXISTS %s (
            %s,
            %s VARCHAR(255) NOT NULL UNIQUE,
            %s TEXT NOT NULL,
            %s
        )
        """, tableName, idDefinition, COLUMN_KEY, COLUMN_MESSAGE, createdAtDefinition);
    }

    /**
     * Asynchronously stores or deletes a verification metadata message.
     *
     * <p>If {@code message} is non-empty, any existing row for {@code keyId} is deleted
     * first (upsert semantics), then the new row is inserted.</p>
     *
     * <p>If {@code message} is empty (or blank), the existing row for {@code keyId}
     * is deleted — this is the revocation signal as defined by {@link MetadataBroker}.</p>
     *
     * @param keyId   the Protocol V2 {@code messageId} or reserved key; must not be {@code null}
     * @param message the Protocol V2 metadata message to store; an empty string signals revocation
     * @return a {@link java.util.concurrent.CompletableFuture} that completes when the
     *         database operation finishes, or completes exceptionally on SQL error
     */
    @Override
    public CompletableFuture<Void> send(String keyId, String message) {
        return CompletableFuture.runAsync(() -> {
            try (Connection conn = dataSource.getConnection()) {
                if (keyId == null || keyId.isBlank() || message == null) return;

                if (message.isBlank()) { // Delete the record with keyId
                    removeEntry(keyId, conn);
                } else { // save a new records with that keyId
                    // Transactional upsert: delete then insert in a single transaction block to prevent concurrent duplicates (H8)
                    conn.setAutoCommit(false);
                    try {
                        removeEntry(keyId, conn);

                        String sql = String.format(
                                "INSERT INTO %s (%s, %s) VALUES (?, ?)",
                                tableName, COLUMN_KEY, COLUMN_MESSAGE
                        );

                        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                            stmt.setString(1, keyId);
                            stmt.setString(2, message);
                            stmt.executeUpdate();
                        }
                        conn.commit();
                    } catch (SQLException e) {
                        conn.rollback();
                        throw e;
                    } finally {
                        conn.setAutoCommit(true);
                    }
                }

            } catch (SQLException e) {
                throw new RuntimeException("Failed to store message in DB", e);
            }
        });
    }

    // Remove entry from the secured keys
    private void removeEntry(String keyId, Connection conn) throws SQLException {
        String sql = String.format(
                "DELETE FROM %s WHERE %s = ?",
                tableName, COLUMN_KEY
        );

        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, keyId);
            stmt.executeUpdate();
        }
    }

    /**
     * Retrieves the verification metadata message for the given key from the database.
     *
     * <p>Returns the first (oldest) matching row. If no row exists (key unknown or
     * already revoked), a {@link BrokerExtractionException} is thrown.</p>
     *
     * @param keyId the Protocol V2 {@code messageId} or reserved key; must not be {@code null}
     * @return the stored metadata message; never {@code null} or empty
     * @throws BrokerExtractionException if no row is found, or if a SQL error occurs
     */
    @Override
    public String get(String keyId) {
        try (Connection conn = dataSource.getConnection()) {
            String sql = String.format(
                    "SELECT %s FROM %s WHERE %s = ? ORDER BY created_at",
                    COLUMN_MESSAGE, tableName, COLUMN_KEY
            );

            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, keyId);
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    return rs.getString(COLUMN_MESSAGE);
                } else {
                    throw new BrokerExtractionException("Message not found for key: " + keyId);
                }
            }
        } catch (SQLException e) {
            logger.severe(e.getMessage());
            throw new BrokerExtractionException("Failed to retrieve message from DB for key: " + keyId);
        }
    }

    /**
     * Returns all keys stored in the database whose value starts with the given prefix.
     *
     * <p>Uses a SQL {@code LIKE} query ({@code prefix%}) to locate matching rows.
     * The result set is not ordered.</p>
     *
     * @param prefix the key prefix to search for (e.g., {@code "2:user-123:"})
     * @return a list of matching keys; empty if none found (never {@code null})
     * @throws BrokerExtractionException if a SQL error occurs during the query
     */
    @Override
    public List<String> getKeysByPrefix(String prefix) throws BrokerExtractionException {
        List<String> keys = new ArrayList<>();
        try (Connection conn = dataSource.getConnection()) {
            String sql = String.format(
                    "SELECT %s FROM %s WHERE %s LIKE ? ESCAPE '!'",
                    COLUMN_KEY, tableName, COLUMN_KEY
            );
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, escapeLikePattern(prefix) + "%");
                ResultSet rs = stmt.executeQuery();
                while (rs.next()) {
                    keys.add(rs.getString(COLUMN_KEY));
                }
            }
        } catch (SQLException e) {
            logger.severe(e.getMessage());
            throw new BrokerExtractionException(
                    "Failed to retrieve keys by prefix from DB: " + prefix);
        }
        return keys;
    }

    private String escapeLikePattern(String prefix) {
        if (prefix == null) {
            return "";
        }
        return prefix.replace("!", "!!")
                     .replace("%", "!%")
                     .replace("_", "!_");
    }
}
