package io.github.cyfko.veridot.core;

import io.github.cyfko.veridot.core.exceptions.BrokerTransportException;
import io.github.cyfko.veridot.core.exceptions.DataSerializationException;

import java.util.function.Function;

/**
 * Contract for issuing cryptographically signed tokens tied to a payload and a time-bound validity window.
 *
 * <p>Implementations serialize the provided payload, embed it in a signed token, and publish
 * the associated <em>verification metadata</em> to a {@link Broker} so that any service
 * can later verify the token independently — without sharing secrets.</p>
 *
 * <p>The returned token type depends on the chosen {@link DistributionMode}:</p>
 * <ul>
 *   <li>{@link DistributionMode#DIRECT} — the signed token itself is returned to the caller.</li>
 *   <li>{@link DistributionMode#INDIRECT} — a lightweight {@code messageId} is returned;
 *       the token is stored in the broker and retrieved at verification time.</li>
 * </ul>
 *
 * <h2>Typical usage</h2>
 * <pre>{@code
 * DataSigner signer = new GenericSignerVerifier(broker, trustRoot, "my-signer", longTermKey);
 *
 * // Issue a token valid for 1 hour (DIRECT mode — token returned directly)
 * String token = signer.sign("user@example.com",
 *     BasicConfigurer.builder()
 *         .groupId("user-123")
 *         .sequenceId("session-A")   // optional; auto-generated UUID if omitted
 *         .validity(3600)
 *         .build());
 *
 * // Issue a token in INDIRECT mode (only the messageId is returned)
 * String messageId = signer.sign("user@example.com",
 *     BasicConfigurer.builder()
 *         .groupId("user-123")
 *         .distribution(DistributionMode.INDIRECT)
 *         .validity(3600)
 *         .build());
 * }</pre>
 *
 * @author Frank KOSSI
 * @since 1.0.0
 * @see TokenVerifier
 * @see io.github.cyfko.veridot.core.impl.BasicConfigurer
 */
@FunctionalInterface
public interface DataSigner {

    /**
     * Configuration contract for a signing request.
     *
     * <p>Describes the target group, optional sequence, distribution mode, validity duration,
     * and the serialization strategy for the payload. Use {@link io.github.cyfko.veridot.core.impl.BasicConfigurer#builder()} to
     * obtain a ready-to-use implementation.</p>
     */
    interface Configurer {

        /**
         * The group identifier linking the token to a business entity (e.g., userId, serviceId).
         * Maps to the {@code groupId} field in the Protocol V4 {@code messageId}.
         *
         * @return non-null, non-blank string of 1–125 printable characters
         *         (must not contain {@code :}, {@code ,}, {@code |}, or whitespace)
         */
        String getGroupId();

        /**
         * Optional sequence identifier within the group (e.g., session name, device ID).
         * Maps to the {@code sequenceId} field in the Protocol V4 {@code messageId}.
         *
         * <p>If {@code null}, a random UUID is auto-generated by the signer at signing time,
         * guaranteeing uniqueness within the group.</p>
         *
         * @return a string of 1–125 printable characters (must not contain {@code :}, {@code ,},
         *         {@code |}, or whitespace), or {@code null} to trigger auto-generation
         */
        String getSequenceId();

        /**
         * Determines how the signed token is delivered to the caller after signing.
         *
         * @return {@link DistributionMode}, never {@code null}
         * @see DistributionMode
         */
        DistributionMode getDistribution();

        /**
         * The validity window in seconds for which the issued token is considered active.
         *
         * @return a positive number of seconds (e.g., {@code 3600} for one hour)
         */
        long getDuration();

        /**
         * Serializer function responsible for converting the payload object into a
         * transport-safe string (e.g., JSON, base64-encoded bytes, plain text).
         *
         * @return a non-null {@link Function} from {@code Object} to {@code String}
         */
        Function<Object, String> getSerializer();

        /**
         * The list of authorized recipient processor IDs for PRIVATE distribution mode.
         *
         * @return a list of recipient IDs, or an empty list if not specified
         */
        default java.util.List<String> getRecipients() {
            return java.util.Collections.emptyList();
        }

        /**
         * The MIME type of the payload for PRIVATE distribution mode (e.g., "application/json").
         *
         * @return the MIME type string, or null if not specified
         */
        default String getMimeType() {
            return null;
        }
    }

    /**
     * Issues a signed token that embeds the given payload for the specified duration.
     *
     * <p>The payload is serialized using the configurer's {@link Configurer#getSerializer() serializer}
     * and embedded in a cryptographically signed object. Verification metadata (including the public
     * key material and TTL) is simultaneously published to the underlying {@link Broker}
     * so that any downstream service sharing the same broker can verify the token.</p>
     *
     * <p>The return value depends on the configured {@link DistributionMode}:</p>
     * <ul>
     *   <li>{@link DistributionMode#DIRECT} — returns the signed token string directly.</li>
     *   <li>{@link DistributionMode#INDIRECT} — returns the Protocol V4 {@code messageId}
     *       (format: {@code <version>:<groupId>:<sequenceId>}); the token is stored in the broker.</li>
     * </ul>
     *
     * @param data       the payload to embed; must not be {@code null}
     * @param configurer signing configuration; must not be {@code null}
     * @return the issued token (or its {@code messageId} in INDIRECT mode)
     * @throws DataSerializationException if the payload cannot be serialized
     * @throws BrokerTransportException   if publishing verification metadata to the broker fails
     * @throws IllegalArgumentException   if {@code data} is {@code null}, or if configuration
     *                                    values are invalid (e.g., non-positive duration)
     */
    String sign(Object data, Configurer configurer) throws DataSerializationException, BrokerTransportException;
}
