package io.github.cyfko.veridot.core;

import io.github.cyfko.veridot.core.exceptions.BrokerTransportException;
import io.github.cyfko.veridot.core.exceptions.DataSerializationException;

import java.util.function.Function;

/**
 * Functional interface for generating signed tokens using an ephemeral asymmetric private key.
 * <p>
 * Implementations of this interface are responsible for serializing the provided payload object
 * and generating a signed token that remains valid for a specified duration. The resulting token
 * may be a full JWT or a {@code messageId} depending on the selected {@link DistributionMode}.
 * </p>
 *
 * <p>
 * This interface is primarily intended for use in distributed systems where services must issue
 * short-lived, cryptographically verifiable tokens without relying on shared secrets.
 * </p>
 *
 * @author Frank KOSSI
 * @since 1.0.0
 */
@FunctionalInterface
public interface DataSigner {

    interface Configurer {

        /**
         * The group identifier linking the token to a business entity (e.g., userId, serviceId).
         * Maps to the {@code groupId} field in the Protocol V2 messageId.
         *
         * @return non-null, non-blank string of 1-125 printable characters (excluding {@code :,|} and whitespace)
         */
        String getGroupId();

        /**
         * Optional sequence identifier within the group (e.g., session name, device ID).
         * Maps to the {@code sequenceId} field in the Protocol V2 messageId.
         * If {@code null}, a UUID will be auto-generated by the signer.
         *
         * @return a string of 1-125 printable characters (excluding {@code :,|} and whitespace), or {@code null}
         */
        String getSequenceId();

        /**
         * How the signed token is delivered to the caller.
         *
         * @return {@link DistributionMode}, never {@code null}
         */
        DistributionMode getDistribution();

        /**
         * Get the duration in seconds for which the token should remain valid; must be positive.
         *
         * @return positive long
         */
        long getDuration();

        /**
         * Serializer function to convert the payload object to a string.
         *
         * @return non-null function
         */
        Function<Object, String> getSerializer();
    }

    /**
     * Generates a signed token that references the given payload for the specified duration.
     *
     * <p>
     * The payload is serialized and embedded in a cryptographically signed JWT structure.
     * The resulting token is a full JWT if {@link DistributionMode#DIRECT},
     * or a Protocol V2 {@code messageId} if {@link DistributionMode#INDIRECT}.
     * </p>
     *
     * @param data       the object to be signed; must not be {@code null}
     * @param configurer signing configuration; must not be {@code null}
     * @return a signed token as a string
     * @throws DataSerializationException if the payload cannot be serialized
     * @throws BrokerTransportException   if propagating metadata to the broker fails
     */
    String sign(Object data, Configurer configurer) throws DataSerializationException, BrokerTransportException;
}
